#!/usr/bin/groovy
def k8s_token = '<unknown>'

node ('master') {
    k8s_token = readFile '/var/run/secrets/kubernetes.io/serviceaccount/token'
}

node('redhatdistortion-maven') {
    def k8s_namespace = readFile '/var/run/secrets/kubernetes.io/serviceaccount/namespace'

    stage 'Checkout SCM'
    checkout scm

    stage 'Openshift login'
    sh "oc login https://kubernetes.default/ --token=${k8s_token} --certificate-authority=/run/secrets/kubernetes.io/serviceaccount/ca.crt"
//  Prepare the deployments so you can see pipeline in console overview when running for the first time
    sh 'oc process -f helloworld/.openshift-ci_cd/empty-deployment-template.yaml -v "APP_NAME=helloworld-dev" | oc apply -f -'
//    sh 'oc process -f helloworld/.openshift-ci_cd/empty-deployment-template.yaml -v "APP_NAME=helloworld-test" | oc apply -f -'
//    sh 'oc process -f helloworld/.openshift-ci_cd/empty-deployment-template.yaml -v "APP_NAME=helloworld-prod" | oc apply -f -'

    stage 'Build'
    sh 'cd helloworld && mvn clean compile'

    stage 'Run Unit Tests'
    sh 'cd helloworld && mvn test'

    stage 'Package'
    sh 'cd helloworld && mvn package'

    stage 'Archive artifact'
    archive 'helloworld/target/*.war'

    stage 'Create Image'
    sh 'oc delete bc helloworld || true'  // Bugfix for https://github.com/openshift/origin/issues/9301
    sh 'oc process -f https://github.com/tnozicka/openshift-templates/raw/master/binary-build-template.yaml -v "APP_NAME=helloworld,BUILDER_IMAGE=registry.access.redhat.com/jboss-eap-7/eap70-openshift,OUTPUT_IMAGESTREAM_TAG=helloworld:latest" | oc apply -f -'
    sh 'mkdir -p ../artifacts/deployments/ && cp helloworld/target/*.war ../artifacts/deployments/'
    sh 'oc start-build helloworld --from-dir=../artifacts/ --follow'

    stage 'Deploy to dev'
    sh "oc process -f helloworld/.openshift-ci_cd/deployment-template.yaml -v 'APP_NAME=helloworld-dev,IMAGE_STREAM_NAMESPACE=${k8s_namespace},IMAGE_STREAM_TAG=helloworld:latest' | oc apply -f -"

//    stage 'Deploy to test'
//    input 'Confirm deploying to test.'
//    sh "oc process -f helloworld/.openshift-ci_cd/deployment-template.yaml -v 'APP_NAME=helloworld-test,IMAGE_STREAM_NAMESPACE=${k8s_namespace},IMAGE_STREAM_TAG=helloworld:latest' | oc apply -f -"

//    stage 'Deploy to production'
//    input 'Confirm deploying to production.'
//    sh "oc process -f helloworld/.openshift-ci_cd/deployment-template.yaml -v 'APP_NAME=helloworld-prod,IMAGE_STREAM_NAMESPACE=${k8s_namespace},IMAGE_STREAM_TAG=helloworld:latest' | oc apply -f -"
}
